services:
    hd_wallet:
        image: hd_wallet
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        command: python app/main.py
        env_file:
            - .env
        volumes:
            - .:/hd_wallet_rest_api
        ports:
            - "8080:8080"
        depends_on:
            hd_wallet_db:
                condition: service_healthy
        networks:
            - localhd_wallet

    hd_wallet_db:
        image: postgres:latest
        env_file:
            - .env
        volumes:
            - database-hd-wallet:/var/lib/postgresql@17/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        networks:
            - localhd_wallet

volumes:
    database-hd-wallet:

networks:
    localhd_wallet:
        name: localhd_wallet
        external: true
