"""empty message

Revision ID: 95b5aaea57d9
Revises: 
Create Date: 2024-12-18 20:23:44.848526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b5aaea57d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False, comment='Wallet index'),
    sa.Column('address', sa.String(), nullable=False, comment='Wallet address'),
    sa.Column('private_key', sa.String(), nullable=False, comment='Wallet private key'),
    sa.Column('public_key', sa.String(), nullable=False, comment='Wallet public key'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('private_key'),
    sa.UniqueConstraint('public_key')
    )
    op.create_index(op.f('ix_wallet_address'), 'wallet', ['address'], unique=True)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False, comment='Currency code'),
    sa.Column('amount', sa.Float(), nullable=False, comment='Amount transaction'),
    sa.Column('wallet_id', sa.Integer(), nullable=False, comment='Wallet id that make the transaction'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_index(op.f('ix_wallet_address'), table_name='wallet')
    op.drop_table('wallet')
    # ### end Alembic commands ###
