"""add_transaction_hash

Revision ID: 9acc30e0e80d
Revises: 95b5aaea57d9
Create Date: 2024-12-18 22:05:35.960701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9acc30e0e80d'
down_revision: Union[str, None] = '95b5aaea57d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('transaction_hash', sa.String(), nullable=True, comment='Transaction hash'))
    op.alter_column('transaction', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_comment='Amount transaction',
               existing_nullable=False)
    op.create_unique_constraint(None, 'transaction', ['transaction_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='unique')
    op.alter_column('transaction', 'amount',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='Amount transaction',
               existing_nullable=False)
    op.drop_column('transaction', 'transaction_hash')
    # ### end Alembic commands ###
